export const dynamic = 'force-dynamic';
import Link from 'next/link';
import { db } from '../lib/db';
import { whatsappUrl,generalWhatsAppMessage } from '../lib/whatsapp';
export default async function Home(){
 const [products,collections,testimonials,offer]=await Promise.all([db.product.findMany({where:{visibility:'PUBLISHED',featured:true},take:4,orderBy:{createdAt:'desc'}}),db.collection.findMany({where:{published:true},take:4,orderBy:{createdAt:'asc'}}),db.testimonial.findMany({where:{published:true},take:3}),db.offer.findFirst({where:{active:true,endDate:{gte:new Date()}},orderBy:{endDate:'asc'}})]);
 return <main>
 <section className="hero"><div className="container hero-grid"><div><div className="eyebrow">Indian city stories, crafted in cotton</div><h1>Wear your city.</h1><p>Premium cotton T-shirts inspired by the places, craft and culture that make Indian cities unforgettable.</p><div className="hero-actions"><Link className="btn primary" href="/shop">Explore the collection</Link><a className="btn ghost" href={whatsappUrl(generalWhatsAppMessage)}>Chat on WhatsApp</a></div></div><div className="hero-art"><img src="/logo.png" alt="CottonCrafted emblem"/></div></div></section>
 {offer&&<section className="container section" style={{paddingBottom:0}}><div className="offer"><div className="offer-inner"><div><div className="eyebrow" style={{color:'#e8d7c5'}}>Limited offer</div><h3 style={{margin:'8px 0',color:'#fff'}}>{offer.bannerText||offer.name}</h3><span>Code: <b>{offer.code}</b></span></div><Link className="btn" href="/shop">{offer.cta||'Shop now'}</Link></div></div></section>}
 <section className="container section"><div className="section-head"><div><div className="eyebrow">The drop</div><h2>Featured pieces</h2></div><Link href="/shop">View all →</Link></div><div className="grid">{products.map(p=><Link className="card" key={p.id} href={`/product/${p.slug}`}><div className="card-img"><img src={(p.images as string[])[0]} alt={p.name}/></div><div className="card-body"><h3>{p.name}</h3><div className="price">₹{p.salePrice||p.price}{p.salePrice&&<span className="old">₹{p.price}</span>}</div></div></Link>)}</div></section>
 <section className="section" style={{background:'#efe7dc'}}><div className="container story"><div><div className="eyebrow">Why CottonCrafted</div><h2>Cities become stories. Stories become something you can wear.</h2><p className="story-copy">From the ghats of Varanasi to the streets of Delhi and the craft traditions of Lucknow, every drop translates a city detail into a clean, modern wardrobe piece.</p><a className="btn primary" href={whatsappUrl(generalWhatsAppMessage)}>Ask about the collection</a></div><div className="hero-art"><img src="/logo.png" alt="CottonCrafted"/></div></div></section>
 <section className="container section"><div className="section-head"><div><div className="eyebrow">Explore</div><h2>Collections</h2></div></div><div className="grid">{collections.map(c=><Link className="card" key={c.id} href={`/collections#${c.slug}`}><div className="card-img"><img src={c.image||'/logo.png'} alt={c.name}/></div><div className="card-body"><h3>{c.name}</h3><span className="muted">Discover the story →</span></div></Link>)}</div></section>
 {testimonials.length>0&&<section className="section" style={{background:'#f1ebe2'}}><div className="container"><div className="eyebrow">From the community</div><h2>What people say</h2><div className="grid">{testimonials.map(t=><div className="card" key={t.id}><div className="card-body"><div>★★★★★</div><p>“{t.review}”</p><b>{t.customerName}</b></div></div>)}</div></div></section>}
 </main>
}
