'use client'; import {useState} from 'react';
const configs:any={
 categories:{title:'Categories',endpoint:'/api/categories',fields:[['name','Name'],['slug','Slug'],['description','Description'],['image','Image URL']]},
 collections:{title:'Collections',endpoint:'/api/collections',fields:[['name','Name'],['slug','Slug'],['description','Description'],['image','Image URL']]},
 pages:{title:'Pages',endpoint:'/api/pages',fields:[['title','Title'],['slug','Slug'],['heroImage','Hero image URL'],['content','Sections JSON (hero/text/image/cta blocks)'],['seoTitle','SEO title'],['seoDescription','SEO description']]},
 offers:{title:'Offers',endpoint:'/api/offers',fields:[['name','Name'],['discountType','Discount type'],['discountAmount','Discount amount'],['code','Code'],['bannerText','Banner text'],['cta','CTA'],['startDate','Start date'],['endDate','End date']]},
 testimonials:{title:'Testimonials',endpoint:'/api/testimonials',fields:[['customerName','Customer name'],['review','Review'],['image','Image URL'],['rating','Rating']]},
 navigation:{title:'Navigation',endpoint:'/api/navigation',fields:[['label','Label'],['href','URL'],['sortOrder','Order']]}
};
export default function ResourceManager({kind,initial}:{kind:keyof typeof configs,initial:any[]}){const c=configs[kind];const [items,setItems]=useState(initial),[editing,setEditing]=useState<any>(null);const blank:any=Object.fromEntries(c.fields.map((x:any)=>[x[0],'' ]));async function save(e:any){e.preventDefault();const form=new FormData(e.currentTarget);const payload:any=Object.fromEntries(form.entries());for(const n of ['discountAmount','rating','sortOrder'])if(payload[n])payload[n]=Number(payload[n]);if(kind==='pages'){try{payload.content=JSON.parse(payload.content||'[]')}catch{alert('Sections JSON is invalid');return}}if(kind==='offers'){payload.startDate=new Date(payload.startDate).toISOString();payload.endDate=new Date(payload.endDate).toISOString()}const res=await fetch(c.endpoint,{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing?{id:editing.id,...payload}:payload)});if(res.ok){const d=await res.json();setItems(editing?items.map(x=>x.id===d.id?d:x):[d,...items]);setEditing(null);e.currentTarget.reset()}}async function del(id:string){if(!confirm('Delete this item?'))return;await fetch(c.endpoint+'?id='+id,{method:'DELETE'});setItems(items.filter(x=>x.id!==id))}return <><div className="admin-top"><div><div className="eyebrow">CMS</div><h1 style={{fontSize:50}}>{c.title}</h1></div></div><div className="card" style={{padding:20,marginBottom:25}}><form onSubmit={save}><div className="form-grid">{c.fields.map(([name,label]:any)=><div key={name}><label>{label}</label>{name==='content'?<textarea name={name} className="input" rows={8} defaultValue={editing?.[name]?JSON.stringify(editing[name],null,2):'[]'}/>:<input name={name} className="input" defaultValue={editing?.[name] instanceof Date?new Date(editing[name]).toISOString().slice(0,16):editing?.[name]||''} type={name.includes('Date')?'datetime-local':'text'} required={['name','title','slug','customerName','review','label','href'].includes(name)}/>} </div>)}</div><div style={{marginTop:15,display:'flex',gap:10}}><button className="btn primary">{editing?'Save':'Create'}</button>{editing&&<button type="button" className="btn" onClick={()=>setEditing(null)}>Cancel</button>}</div></form></div><table className="table"><thead><tr><th>Item</th><th>Status</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.name||x.title||x.customerName||x.label}</td><td>{x.published===false?'DRAFT':'Active'}</td><td><button className="btn" onClick={()=>setEditing(x)}>Edit</button> <button className="btn" onClick={()=>del(x.id)}>Delete</button></td></tr>)}</tbody></table></>}
